name: leap_publications

resources:
  cloud: gcp
  region: us-central1
  instance_type: n4-standard-4
  use_spot: false

workdir: .

envs:
  ADS_API_TOKEN: ""
  OUTPUT_PATH: "gs://leap-persistent/publications/LEAP_Publications.xlsx"

setup: |
  curl -LsSf https://astral.sh/uv/install.sh | sh

run: |
  set -e
  source $HOME/.local/bin/env
  PYTHONUNBUFFERED=1 uv run batch.py