name: large_batch

resources:
  cloud: gcp
  region: us-central1
  instance_type: n4-highmem-8
  use_spot: false
  # disk_size: 100
  autostop:
    idle_minutes: 5
    down: true

workdir: .

setup: |
  curl -LsSf https://astral.sh/uv/install.sh | sh

run: |
  source $HOME/.local/bin/env
  echo "Starting large batch job example"
  uv run batch.py
  echo "Job completed"
