name: dadapy_batch

resources:
  cloud: gcp
  region: us-central1
  instance_type: n4-standard-8
  use_spot: false
  # disk_size: 100
  autostop:
    idle_minutes: 5
    down: true

workdir: .

envs:
  N: 16000
  RANDOM_STATE: 10
  N_EPOCHS: 80
  OUTPUT_PATH: gs://leap-scratch/dadapy/SOCAT

setup: |
  set -e
  sudo apt-get update
  sudo apt-get install -y build-essential
  curl -LsSf https://astral.sh/uv/install.sh | sh

run: |
  set -e
  source $HOME/.local/bin/env
  echo "Starting batch"
  uv run --python 3.12 batch.py
  echo "Job completed"
